project_id = "ijotcekseqoasueihvsh"

[functions.analyze-food]
verify_jwt = false

[functions.revenuecat]
verify_jwt = false

[functions.barcode-lookup]
verify_jwt = false

[functions.push-notifications]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false

[functions.cleanup-deleted-accounts]
verify_jwt = false

[functions.enqueue-food-analysis]
verify_jwt = true

[functions.process-food-analysis]
verify_jwt = false

[functions.get-job-status]
verify_jwt = true

[functions.cached-stats]
verify_jwt = true